replicaCount: 1

image:
  repository: alpine/socat
  tag: 1.7.4.4
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

tunnel:
  host: myhost
  port: 9999
  localPort: 9999
