---
apiVersion: {{ (include "cronjobber.rbacApiVersion" .) | required "Unable to determine RBAC apiVersion for ClusterRole and none explicitly set." }}
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
rules:
  - apiGroups: ['cronjobber.hidde.co']
    resources: ['*']
    verbs: ['*']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'patch', 'update']
