---
apiVersion: {{ (include "cronjobber.rbacApiVersion" .) | required "Unable to determine RBAC apiVersion for ClusterRoleBinding and none explicitly set." }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "cronjobber.fullname" . }}
  labels:
    {{- include "cronjobber.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cronjobber.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cronjobber.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
