---
{{ $apiVersion := (include "cronjobber.crdApiVersion" .) | required "Unable to determine apiVersion for CustomResourceDefinition and none explicitly set." }}
apiVersion: {{ $apiVersion }}
kind: CustomResourceDefinition
metadata:
  name: tzcronjobs.cronjobber.hidde.co
spec:
  group: cronjobber.hidde.co
  {{- if eq $apiVersion "apiextensions.k8s.io/v1beta1" }}
  version: v1alpha1
  {{- end }}
  names:
    plural: tzcronjobs
    singular: tzcronjob
    kind: TZCronJob
    listKind: TZCronJobList
    shortNames:
      - tzc
  scope: Namespaced
  {{- if eq $apiVersion "apiextensions.k8s.io/v1beta1" }}
  subresources:
    status: {}
  additionalPrinterColumns: {{- include "cronjobber.crdAdditionalPrinterColumns" . | nindent 4 }}
  {{- end }}
  {{- if eq $apiVersion "apiextensions.k8s.io/v1" }}
  versions:
    - additionalPrinterColumns: {{- include "cronjobber.crdAdditionalPrinterColumns" . | nindent 8 }}
      name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required:
            - metadata
            - spec
          type: object
  {{- end }}
