name: cronjobber
namespace: default
image:
  repository: quay.io/hiddeco/cronjobber
  tag: 0.3.0
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
sidecar:
  enabled: false
  name: init-updatetz
  image:
    repository: quay.io/hiddeco/cronjobber-updatetz
    tag: 0.1.1
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
  # NB: the security context configuration below may not work
  # out of the box on OpenShift
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
nodeSelector: {}

rbac:
  apiVersion: null
  apiVersionPolicy:
    newestAvailable: false
    candidateApiVersions:
      - rbac.authorization.k8s.io/v1beta1
      - rbac.authorization.k8s.io/v1

crd:
  apiVersion: null
  apiVersionPolicy:
    newestAvailable: false
    candidateApiVersions:
      - apiextensions.k8s.io/v1beta1
      - apiextensions.k8s.io/v1
